# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 18:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplie',
            name='barcode',
            field=models.IntegerField(help_text='(Código de barras de 13 digitos)', validators=[django.core.validators.MaxValueValidator(9999999999999)]),
        ),
    ]
