# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 18:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_auto_20160908_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplie',
            name='barcode',
            field=models.PositiveIntegerField(help_text='(Código de barras de 13 digitos)', validators=[django.core.validators.MaxValueValidator(13)]),
        ),
    ]
