# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0004_auto_20160908_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplie',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
