# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 17:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0005_auto_20160908_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplie',
            name='price',
        ),
        migrations.AlterField(
            model_name='supplie',
            name='barcode',
            field=models.PositiveIntegerField(blank=True, help_text='(Código de barras de 13 digitos)', validators=[django.core.validators.MaxValueValidator(9999999999999)]),
        ),
    ]
