# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 17:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0006_auto_20160919_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplie',
            name='barcode',
            field=models.PositiveIntegerField(blank=True, help_text='(Código de barras de 13 digitos)', null=True, validators=[django.core.validators.MaxValueValidator(9999999999999)]),
        ),
    ]
