# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0008_auto_20160919_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplie',
            name='Category',
        ),
        migrations.AlterField(
            model_name='supplie',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supplies.Category'),
        ),
    ]
