# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0010_auto_20160926_1340'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supplie',
            new_name='Supply',
        ),
    ]
