# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0011_auto_20160926_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supply',
            options={'ordering': ('id',), 'verbose_name': 'Supply', 'verbose_name_plural': 'Supplies'},
        ),
    ]
