# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0013_auto_20160926_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supplies.Category'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supplies.Provider'),
        ),
    ]
