# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0015_auto_20161001_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
