# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 09:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to=b'')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to=b'')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('barcode', models.PositiveIntegerField(blank=True, help_text='(Codigo de barras de 13 digitos)', null=True, validators=[django.core.validators.MaxValueValidator(9999999999999)])),
                ('image', models.ImageField(upload_to=b'')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supplies.Category')),
                ('provider', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supplies.Provider')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Supply',
                'verbose_name_plural': 'Supplies',
            },
        ),
    ]
