# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('1', 'Provider'), ('2', 'Stock'), ('3', 'Assemblied'), ('4', 'Selled')], max_length=1)),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Stock Chain',
                'verbose_name_plural': 'Stocks Chain',
            },
        ),
        migrations.AddField(
            model_name='supply',
            name='ideal_durability',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='stockchain',
            name='supply',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supplies.Supply'),
        ),
    ]
