# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_auto_20161013_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='parent_metric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.Metric'),
        ),
        migrations.AlterField(
            model_name='stockchain',
            name='status',
            field=models.CharField(choices=[('1', 'Provider'), ('2', 'Stock'), ('3', 'Assemblied'), ('4', 'Selled')], default=1, max_length=1),
        ),
    ]
