# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0004_auto_20161013_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metric',
            options={'ordering': ('id',), 'verbose_name': 'Stock Chain', 'verbose_name_plural': 'Stocks Chain'},
        ),
        migrations.AlterField(
            model_name='metric',
            name='metric_type',
            field=models.CharField(choices=[('gramos', 'gramos'), ('litros', 'litros'), ('empaques', 'empaques'), ('cajas', 'cajas')], max_length=8),
        ),
    ]
