# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0005_auto_20161013_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metric',
            options={'ordering': ('id',), 'verbose_name': 'Metric', 'verbose_name_plural': 'Metrics'},
        ),
    ]
