# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0006_auto_20161013_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartdrige',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Cartridge',
                'verbose_name_plural': 'Cartridges',
            },
        ),
        migrations.CreateModel(
            name='PackageCartridges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Package Cartridges',
                'verbose_name_plural': 'Packages Cartridges',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=125, unique=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='name',
            field=models.CharField(max_length=125, unique=True),
        ),
        migrations.AddField(
            model_name='cartdrige',
            name='packageCartridges_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.PackageCartridges'),
        ),
        migrations.AddField(
            model_name='stockchain',
            name='cartridge_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.Cartdrige'),
        ),
    ]
