# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 17:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0009_auto_20161013_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartridge',
            options={'ordering': ('id',), 'verbose_name': 'Cartridge', 'verbose_name_plural': 'Cartridges'},
        ),
        migrations.RemoveField(
            model_name='cartridge',
            name='name',
        ),
        migrations.AddField(
            model_name='cartridge',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
