# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 17:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0010_auto_20161017_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
