# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0012_auto_20161017_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockchain',
            name='registered_at',
            field=models.DateField(auto_now=True),
        ),
    ]
