# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0013_auto_20161017_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
