# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 01:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0015_remove_cartridge_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegisters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default=((1, 'Active'), (2, 'Off')), max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(default=1, max_length=10, verbose_name=((1, 'empaques'), (2, 'cajas')))),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.Lot')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lots',
            },
        ),
        migrations.RemoveField(
            model_name='metric',
            name='parent_metric',
        ),
        migrations.AddField(
            model_name='cartridge',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='stockchain',
            name='metric',
            field=models.CharField(default=1, max_length=2, verbose_name=((1, 'lt'), (2, 'gr'))),
        ),
        migrations.AlterField(
            model_name='stockchain',
            name='status',
            field=models.CharField(choices=[(1, 'Provider'), (2, 'Stock'), (3, 'Assembled'), (4, 'Selled')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='supply',
            name='barcode',
            field=models.PositiveIntegerField(blank=True, help_text='(C\xf3digo de barras de 13 d\xedgitos)', null=True, validators=[django.core.validators.MaxValueValidator(9999999999999)]),
        ),
        migrations.DeleteModel(
            name='Metric',
        ),
    ]
