# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0016_auto_20161021_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartridge',
            name='packageCartridges_id',
        ),
        migrations.AddField(
            model_name='cartridge',
            name='packageCartridges',
            field=models.ManyToManyField(to='supplies.PackageCartridges'),
        ),
        migrations.AlterField(
            model_name='cashregisters',
            name='status',
            field=models.CharField(choices=[('AC', 'Activa'), ('OF', 'Descativa')], default='AC', max_length=10),
        ),
        migrations.AlterField(
            model_name='lot',
            name='metric',
            field=models.CharField(choices=[('PA', 'empaques'), ('BO', 'cajas')], default='PA', max_length=10),
        ),
        migrations.AlterField(
            model_name='stockchain',
            name='metric',
            field=models.CharField(choices=[('GR', 'gramo'), ('LI', 'litro')], default='GR', max_length=2),
        ),
        migrations.AlterField(
            model_name='stockchain',
            name='status',
            field=models.CharField(choices=[('PR', 'Provider'), ('ST', 'Stock'), ('AS', 'Assembled'), ('SO', 'Sold')], default='PR', max_length=15),
        ),
    ]
