# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0017_auto_20161021_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagecartridges',
            name='description',
        ),
        migrations.AddField(
            model_name='packagecartridges',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
