# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0018_auto_20161023_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IP', 'En proceso'), ('RE', 'Recibido'), ('CA', 'Cancelado')], default='IP', max_length=2)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
