# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0019_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='supplies',
            field=models.ManyToManyField(to='supplies.Supply'),
        ),
    ]
