# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0020_order_supplies'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('metric', models.CharField(choices=[('GR', 'gramo'), ('LI', 'litro'), ('PI', 'pieza'), ('PA', 'paquete'), ('BO', 'caja')], default='BO', max_length=2)),
                ('cost', models.FloatField(default=1)),
                ('order', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supplies.Order')),
                ('supply', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supplies.Supply')),
            ],
        ),
        migrations.AlterField(
            model_name='lot',
            name='metric',
            field=models.CharField(choices=[('GR', 'gramo'), ('LI', 'litro'), ('PI', 'pieza'), ('PA', 'paquete'), ('BO', 'caja')], default='PA', max_length=10),
        ),
        migrations.AlterField(
            model_name='stockchain',
            name='metric',
            field=models.CharField(choices=[('GR', 'gramo'), ('LI', 'litro'), ('PI', 'pieza'), ('PA', 'paquete'), ('BO', 'caja')], default='GR', max_length=10),
        ),
    ]
