# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0021_auto_20161024_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='supplies',
        ),
    ]
