# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0022_remove_order_supplies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordersdetails',
            options={'ordering': ('id',), 'verbose_name': 'Order Details', 'verbose_name_plural': 'Orders Details'},
        ),
    ]
