# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0023_auto_20161024_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sucursal', max_length=90)),
                ('addres', models.CharField(default='', max_length=255)),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Branch Office',
                'verbose_name_plural': 'Branch Offices',
            },
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AC', 'Activa'), ('OF', 'Descativa')], default='AC', max_length=10)),
                ('branch_office', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supplies.BranchOffice')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Cash Register',
                'verbose_name_plural': 'Cash Registers',
            },
        ),
        migrations.DeleteModel(
            name='CashRegisters',
        ),
    ]
