# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 13:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0027_auto_20161024_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartridge',
            name='price',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='status',
            field=models.CharField(choices=[(b'AC', b'On'), (b'OF', b'Off')], default=b'AC', max_length=10),
        ),
        migrations.AlterField(
            model_name='supply',
            name='barcode',
            field=models.PositiveIntegerField(blank=True, help_text=b'(C\xc3\xb3digo de barras de 13 d\xc3\xadgitos)', null=True, validators=[django.core.validators.MaxValueValidator(9999999999999)]),
        ),
    ]
