# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 19:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0028_auto_20161025_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='order',
            name='expiry_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='status',
            field=models.CharField(choices=[('AC', 'On'), ('OF', 'Off')], default='AC', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='supply',
            name='barcode',
            field=models.PositiveIntegerField(blank=True, help_text='(Código de barras de 13 dígitos)', null=True, validators=[django.core.validators.MaxValueValidator(9999999999999)]),
        ),
        migrations.AlterField(
            model_name='supply',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.DeleteModel(
            name='Lot',
        ),
    ]
