# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0029_auto_20161027_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expiry_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
