# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0030_auto_20161027_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('IP', 'Pedido'), ('RE', 'Recibido'), ('CA', 'Cancelado')], default='IP', max_length=2),
        ),
        migrations.AlterField(
            model_name='stockchain',
            name='expiry_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stockchain',
            name='registered_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
