# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import supplies.models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0031_auto_20161027_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartridge',
            name='category',
            field=models.CharField(default=1, max_length=15, verbose_name=supplies.models.Category),
        ),
    ]
