# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0035_auto_20161027_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tickets',
                'ordering': ('id',),
                'verbose_name': 'Ticket ',
            },
        ),
        migrations.CreateModel(
            name='TicketDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cartridge', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supplies.Cartridge')),
                ('package_cartridges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.PackageCartridges')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.Ticket')),
            ],
            options={
                'verbose_name_plural': 'Tickets Details',
                'ordering': ('id',),
                'verbose_name': 'Ticket Details',
            },
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='code',
            field=models.CharField(default='Cash_', max_length=5),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cash_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.CashRegister'),
        ),
    ]
