# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0037_auto_20161028_1617'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockChain',
            new_name='Warehouse',
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ('id',), 'verbose_name': 'Warehouse', 'verbose_name_plural': 'Warehouse'},
        ),
    ]
