# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 00:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0039_auto_20161028_1909'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockChain',
            new_name='Warehouse',
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ('id',), 'verbose_name': 'Warehouse', 'verbose_name_plural': 'Warehouse'},
        ),
        migrations.RenameField(
            model_name='branchoffice',
            old_name='addres',
            new_name='address',
        ),
    ]
