# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0040_auto_20161028_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='requirement',
            field=models.CharField(choices=[('DR', 'Ambiente Seco'), ('RE', 'Refrigeración'), ('FR', 'Congelación')], default='DR', max_length=2),
        ),
    ]
