# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0041_supply_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=90)),
                ('branch_office', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supplies.BranchOffice')),
            ],
            options={
                'verbose_name': 'Supplies Location',
                'ordering': ('id',),
                'verbose_name_plural': 'Supplies Locations',
            },
        ),
        migrations.AlterModelOptions(
            name='cashregister',
            options={'ordering': ('id',), 'verbose_name': 'Ticket Details', 'verbose_name_plural': 'Tickets Details'},
        ),
        migrations.AlterModelOptions(
            name='ticketdetails',
            options={},
        ),
        migrations.RenameField(
            model_name='supply',
            old_name='ideal_durability',
            new_name='optimal_duration',
        ),
        migrations.AddField(
            model_name='supply',
            name='optimal_duration_unit',
            field=models.CharField(choices=[('DA', 'DA'), ('MO', 'MO'), ('YE', 'YE')], default='DA', max_length=2),
        ),
        migrations.AddField(
            model_name='supply',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supplies.SupplyLocation'),
        ),
    ]
