# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0042_auto_20161028_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashregister',
            options={'ordering': ('id',), 'verbose_name': 'Cash Register', 'verbose_name_plural': 'Cash Registers'},
        ),
        migrations.AlterModelOptions(
            name='ticketdetails',
            options={'ordering': ('id',), 'verbose_name': 'Ticket Details', 'verbose_name_plural': 'Tickets Details'},
        ),
        migrations.AlterField(
            model_name='cartridge',
            name='category',
            field=models.CharField(default='FD', max_length=2, verbose_name=(('FD', 'Platillos'), ('DR', 'Bebidas'))),
        ),
    ]
