# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0044_auto_20161029_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='code',
            field=models.CharField(default='Cash_', max_length=9),
        ),
    ]
