# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0045_auto_20161029_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_modified_at',
        ),
    ]
