# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0046_auto_20161029_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='registered_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='cartridge',
            name='packageCartridges',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='metric',
        ),
        migrations.AddField(
            model_name='cartridge',
            name='supplies',
            field=models.ManyToManyField(blank=True, to='supplies.Supply'),
        ),
        migrations.AddField(
            model_name='packagecartridges',
            name='cartridges',
            field=models.ManyToManyField(blank=True, to='supplies.Cartridge'),
        ),
        migrations.AddField(
            model_name='supply',
            name='base_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='supply',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticketdetails',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ticketdetails',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='parent_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supplies.Order'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='cartridge_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.Cartridge'),
        ),
    ]
