# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-06 08:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplies', '0004_auto_20170106_0219'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField(auto_created=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PR', 'En proceso'), ('SO', 'Vendido'), ('CA', 'Cancelado')], default='PR', max_length=10)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('score', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('pin', models.CharField(default='1234', max_length=254)),
                ('customer_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Customer Order',
                'verbose_name_plural': 'Customer Orders',
            },
        ),
        migrations.CreateModel(
            name='CustomerOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cartridge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.Cartridge')),
                ('customer_order', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.CustomerOrder')),
                ('package_cartridge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies.PackageCartridge')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Customer Order Detail',
                'verbose_name_plural': 'Customer Order Details',
            },
        ),
    ]
