# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 18:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branchoffices', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_register', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='branchoffices.CashRegister')),
                ('seller', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket ',
                'ordering': ('-created_at',),
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='TicketDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cartridge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Cartridge')),
                ('package_cartridge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.PackageCartridge')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Ticket')),
            ],
            options={
                'verbose_name': 'Ticket Details',
                'ordering': ('id',),
                'verbose_name_plural': 'Tickets Details',
            },
        ),
    ]
